### ISSUE TITLE
bump command returns an error

### ISSUE THREAD

**Issue by PixelIsDed** [valkyrienyanko/partner-bot#2]
As I spoke to you via Email...
The bot has Admin Perms and all variables are entered correctly still the same error occurs that says it didn't find the channel.

**Comment by valkyrienyanko** [comment]
There are many places in the code where channels are trying to be accessed via variables. Check it out yourself. If worse comes to worse you could always just replace everything with a direct channel ID and test further from there.
https://github.com/valkyrienyanko/partner-bot/blob/bbf0f0c63cef45101af7e8c0b8a1e8d5cbe6c98a/bot.js#L47

**Comment by 1kserver** [comment]
bump command error help?
when i do bump it always say in log unknown channel.

**Comment by valkyrienyanko** [comment]
The problem was guild.channels.first() could have been returning a voice channel and not a text channel or could even be returning other types of channels for all we know. Thus this was only working half the time or a good chance it would work on newly created discords without any other channels then text channels.

The issue has been resolved. Sorry for the inconvenience and long wait.
